### ISSUE TITLE
insert cite pag

### ISSUE THREAD

**Issue by Bernardita-coder** [briankavanaugh/APA-7th-Edition#12]
It should insert the page when I insert the quote and it doesn't where I can fix it

**Comment by briankavanaugh** [comment]
I'm not sure what you mean, but it sounds like you are referring to how Word operates, not how the citation is generated.

**Comment by Bernardita-coder** [comment]
yes, theoritacally in word when you reference a page of a book, according to APA 7 it should be p-xx, but with this coder this is no happening. In my case when I do this refering process, it appears "pag" and not "p", so my qestion is how do I fix it.

**Comment by briankavanaugh** [comment]
Does it function differently if APA (6) is selected instead of APA7?

I'll reiterate what I've said on other issues. I'm not the author of this file. I have no more familiarity with it than you probably do. It is primarily Microsoft's, with some updates by others to make it more APA 7 compatible. I've hosted it here as a courtesy so that people can use it and potentially contribute additional fixes to it. If you - or someone else - can find and fix the issue you are describing and submit a pull request, I'll merge it in so others can use it.
