### ISSUE TITLE
Bibliography issue in Spanish language options  

### ISSUE THREAD

**Issue by ArtSan59** [briankavanaugh/APA-7th-Edition#7]
Hey Brian I'm not an expert in coding so I don't know how this should be fixed but I study economics in Venezuela and my thesis needs to be written in Spanish when I add a bibliography into word I receive the reference when I have more than 3 authors like this (Author y otros) instead of (Author et al.)  this needs to be fixed inside of the file for Spanish people education systems because APA 7th requires the use of Latin et al. which means "and others" in English and "y otros" in Spanish

**Comment by briankavanaugh** [comment]
@ArtSan59 I provide this file here as a courtesy, so that others can submit updates or fixes. I am not the author of the file.

Are you referring to the citation or the bibliography entry? It looks to me like the limit is two for a citation. That could be changed.

Line 2764:
`<xsl:variable name="maxCitationAuthors" select="2"/>
`

I also don't see anywhere in the file where it does anything based on language - nor a way to do that. It looks to me it is pulling this from resource strings Microsoft provides external to this file for a citation (starting line 369):

```
  <xsl:template name="templ_str_AndOthersUnCap" >
    <xsl:param name="LCID" />
    <xsl:variable name="_LCID">
      <xsl:call-template name="localLCID">
        <xsl:with-param name="LCID" select="$LCID"/>
      </xsl:call-template>
    </xsl:variable>
    <xsl:value-of select="/*/b:Locals/b:Local[@LCID=$_LCID]/b:Strings/b:AndOthersUnCap"/>
  </xsl:template>
```

For a bibliography entry, I only see it doing ". . ." between the sixth and the last author, if the number of authors is greater than seven. No "et al." at all here.

If the APA6 version isn't doing something different here based on the language, it's not very likely we'll be able to do something different in this file.

**Comment by eztaban** [comment]
@ArtSan59 I am aware that this is old, but for future reference:
When editing the reference itself, you can select the language of the reference. This dictates what is shown in the final citation:
![Example_citation_language](https://github.com/briankavanaugh/APA-7th-Edition/assets/89442974/5d8369d7-10a5-4155-978c-fa1fe5e006a4)

This picture shows a citation, defined as English, and the same citation copied and defined as Greek.
This affects some formatting, also in the bibliography as it will determine something like a subset of pages is written, etc.
For this reason, I would suggest, that this issue should be closed.

**Comment by briankavanaugh** [comment]
@eztaban @ArtSan59 can you take a look at issue #25 and see if I should make the update suggested?

**Comment by eztaban** [comment]
> @eztaban @ArtSan59 can you take a look at issue #25 and see if I should make the update suggested?
> 

Absolutely - I will have a look as soon as i can :)
